dict_caracteristicas_significado = {
  "departamento": "Departamento en el que vive actualmente.",
  "residentes_hogar": "Número de personas que residen en su hogar.",
  "d2_04_num_hijos": "Número de hijos vivos que tiene usted.",
  "per_edad_tipo": "Etapa de desarrollo o edad en la que se encuentra.",
  "estrato_tipo": "Estrato social en el que se encuentra actualmente.",
  "situacion_tipo": "Actividad con la que ocupa usted mayormente su tiempo",
  "frecuencia_consumo_marihuana_tipo": "Frecuencia con la que consume marihuana.",
  "frecuencia_consumo_cocaina_tipo": "Frecuencia con la que consume cocaina.",
  "frecuencia_consumo_basuco_tipo": "Frecuencia con la que consume basuco.",
  "per_sexo_tipo": "Sexo con el que se identifica (Hombre o Mujer).",
  "vive_padre_hogar_tipo": "En su hogar vive o no su padre.",
  "vive_madre_hogar_tipo": "En su hogar vive o no su madre.",
  "vivienda_tipo": "Tipo de vivenda en la que vive actualmente.",
  "d_01_aporta_dinero_hogar_tipo": "Aporta o no economicamente a su hogar.",
  "d_08_estado_salud_tipo": "Estado de salud con el que cuenta actualmente.",
  "d_09_deprimido_tipo": "Se ha sentido deprimido",
  "d_10_poco_interes_tipo": "Poco interes al realizar las cosas que le gustan hacer.",
  "d_11_h_conocimiento_riesgo_fumar_marihuana_frecuentemente_tipo": "Conocimiento sobre el riesgo de consumir marihuana de forma frecuente.",
  "d_11_k_conocimiento_riesgo_cocaina_frecuentemente_tipo": "Conocimiento sobre el riesgo de consumir cocaina de forma frecuente.",
  "d_11_n_conocimiento_riesgo_fumar_basuco_frecuentemente_tipo": "Conocimiento sobre el riesgo de consumir basuco de forma frecuente.",
  "d_12_b_presenta_problema_consumo_sp_barrio_tipo": "En su barrio se presenta o no se presenta el consumo de sustancias psicoactivas.",
  "d_12_c_presenta_problema_expendio_sp_barrio_tipo": "En su barrio se presenta o no se presenta el expendido de sustancias psicoactivas.",
  "d2_01_etnia_tipo": "Etnia a la que pertenece.",
  "d2_03_estado_civil_tipo": "Estado civil en el que se encuentra.",
  "d2_05_nivel_educativo_tipo": "Mayor nivel educativo en el que se encuentra o que ya curso.",
  "g_01_familiares_consumen_sp_tipo": "Sus familiares consumen o no consumen sustancias psicoactivas.",
  "g_02_amigos_consumen_sp_tipo": "Sus amigos consumen o no consumen sustancias psicoactivas.",
  "g_03_curiosidad_probar_sp_tipo": "Ha sentido o no curiosidad por probar sustancias psicoactivas.",
  "g_04_probaria_sp_tipo": "Decision por probar sustancias psicoactivas ",
  "g_05_posibilidad_probar_sp_tipo": "Se le ha presentado la posibilidad o no para probar sustancias psicoactivas.",
  "g_06_a_posibilidad_conseguir_marihuana_tipo": "Facilidad o posibilidad para poder conseguir marihuana.",
  "g_06_b_posibilidad_conseguir_cocaina_tipo": "Facilidad o posibilidad para poder conseguir cocaina.",
  "g_06_c_posibilidad_conseguir_basuco_tipo": "Facilidad o posibilidad para poder conseguir basuco.",
  "g_07_alguien_ofrecio_comprar_probar_sp_tipo": "Le han ofrecido comprar o probar sustencias psicoactivas",
  "g_01_a_num_familiares_consumen_sp_imp_tipo": "Numero de familiares que consumen sustancias psicoactivas.",
  "g_02_a_num_amigos_consumen_sp_imp_tipo": "Numero de amigos que consumen sustancias psicoactivas.",
  "g_08_a_ofrecieron_marihuana_imp_tipo": "Le han ofrecido y hace cuanto tiempo le ofrecieron marihuana.",
  "g_08_b_ofrecieron_cocaina_imp_tipo": "Le han ofrecido y hace cuanto tiempo le ofrecieron cocaina.",
  "g_08_c_ofrecieron_basuco_imp_tipo": "Le han ofrecido y hace cuanto tiempo le ofrecieron basuco."
}